package com.example.weiying.model.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.weiying.model.bean.MyBeans;

import com.example.weiying.model.bean.MyBeansDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig myBeansDaoConfig;

    private final MyBeansDao myBeansDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        myBeansDaoConfig = daoConfigMap.get(MyBeansDao.class).clone();
        myBeansDaoConfig.initIdentityScope(type);

        myBeansDao = new MyBeansDao(myBeansDaoConfig, this);

        registerDao(MyBeans.class, myBeansDao);
    }
    
    public void clear() {
        myBeansDaoConfig.clearIdentityScope();
    }

    public MyBeansDao getMyBeansDao() {
        return myBeansDao;
    }

}
